language: go

go:
  - 1.4
  - tip

before_script:
  - go get -t -v golang.org/x/lint/golint

script:
  - go test -race ./...
  - go vet -x ./...
  - golint . ./...

matrix:
  fast_finish: true
  allow_failures:
    - go: tip